name: Lousville Project CI/CD pipeline

on:
  push:
    branches:
      - main
      - US-156-cicd

jobs:
  build_and_deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'  
    - name: Setup Maven
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        maven-version: '3.9.6'  

    - name: Build with Maven
      run: mvn clean package

    - name: Generate fat Jar
      run: mvn package shade:shade

    - name: List contents of the target folder
      run: dir target /s

    - name: Upload fat Jar to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: target\*.jar  
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}